CREATE USER :PROMOTEUSER
IDENTIFIED BY ":PASSWORD"
DEFAULT TABLESPACE NOACCESS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON tbsdata
QUOTA UNLIMITED ON tbsidx
QUOTA UNLIMITED ON tbsblob
QUOTA UNLIMITED ON tbsclob
